# src/Resources/config/services.yaml
services:
    # Twig Extension
    light_admin.twig_extension:
        class: Tervis\LightAdminBundle\Twig\LightAdminTwigExtension
        public: false
        tags:
            - { name: twig.extension }
    
    # light_admin.twig_extension_runtime:
    #     class: Tervis\LightAdminBundle\Twig\LightAdminTwigExtensionRuntime
    #     public: false
    #     arguments:
    #         - '@Symfony\Component\HttpFoundation\RequestStack'
    #     tags:
    #         - { name: twig.runtime }

    light_admin.field_interface:
        class: Tervis\LightAdminBundle\Contracts\FieldInterface

    # Controllers
    Tervis\LightAdminBundle\Controller\:
        resource: '../../Controller/*'
        autowire: true
        autoconfigure: true
        # arguments:
        #   - '@maker.doctrine_helper'

    light_admin.maker_crud_controller:
        class: Tervis\LightAdminBundle\Maker\MakeCrudController
        arguments:
          - '@maker.doctrine_helper'

