services:
    # Twig Extension
    light_admin.twig_extension:
        class: Tervis\LightAdminBundle\Twig\LightAdminTwigExtension
        public: false
        tags:
            - { name: twig.extension }
    
    light_admin.twig_extension_runtime:
        class: Tervis\LightAdminBundle\Twig\LightAdminTwigExtensionRuntime
        public: false
        arguments:
            - '@Symfony\Component\HttpFoundation\RequestStack'
        tags:
            - { name: twig.runtime }

    Tervis\LightAdminBundle\Contracts\FieldInterface: '@light_admin.field_interface'

    # Controllers
    Tervis\LightAdminBundle\Controller\:
        resource: '../src/Controller/*'
        autowire: true
        autoconfigure: true
        # arguments:
        #   - '@maker.doctrine_helper'


    Tervis\LightAdminBundle\Command\:
        resource: '../src/Maker/*'
        autowire: true
        autoconfigure: true
        arguments:
          - '@maker.doctrine_helper'

